//! Deterministic commands accepted by the PromiseDB state machine.
//!
//! The control API resolves names, generates entity IDs, and constructs commands.
//! The engine applies those commands without randomness or clock access.

use crate::domain::{
    Bundle, CapacityCurve, Choice, PromiseId, ReplacementState, ResourcePoolId, Timestamp, Unit,
    Version,
};
use crate::engine::{
    CapacityRevisionMode, CapacityRevisionOutcome, ChoiceOutcome, HoldOutcome, ReplaceOutcome,
};

/// Opaque identity of a client issuing idempotent commands.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ClientId(String);

impl ClientId {
    /// Creates a client identity from an opaque value.
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    /// Returns the opaque client identity.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// Opaque key identifying one request within a client namespace.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct IdempotencyKey(String);

impl IdempotencyKey {
    /// Creates an idempotency key from an opaque value.
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    /// Returns the opaque key.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// A deterministic request to mutate PromiseDB state.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Command {
    client_id: ClientId,
    idempotency_key: IdempotencyKey,
    operation: CommandOperation,
}

impl Command {
    /// Creates a command with its common idempotency identity.
    pub fn new(
        client_id: ClientId,
        idempotency_key: IdempotencyKey,
        operation: CommandOperation,
    ) -> Self {
        Self {
            client_id,
            idempotency_key,
            operation,
        }
    }

    /// Returns the client namespace for this command.
    pub fn client_id(&self) -> &ClientId {
        &self.client_id
    }

    /// Returns the key identifying this request within its client namespace.
    pub fn idempotency_key(&self) -> &IdempotencyKey {
        &self.idempotency_key
    }

    /// Returns the requested deterministic operation.
    pub fn operation(&self) -> &CommandOperation {
        &self.operation
    }

    pub(crate) fn into_operation(self) -> CommandOperation {
        self.operation
    }
}

/// The mutation requested by a [`Command`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CommandOperation {
    /// Creates a resource pool using an ID generated by the control API.
    CreateResourcePool {
        /// The predetermined pool identity.
        resource_pool_id: ResourcePoolId,
        /// Human-readable pool name.
        display_name: String,
        /// Immutable fixed-point capacity unit.
        unit: Unit,
        /// Initial physical capacity.
        capacity_curve: CapacityCurve,
    },
    /// Replaces a resource pool's complete capacity curve.
    ReviseCapacity {
        /// Pool whose capacity changes.
        resource_pool_id: ResourcePoolId,
        /// Replacement capacity curve.
        capacity_curve: CapacityCurve,
        /// Deficit policy for the revision.
        mode: CapacityRevisionMode,
    },
    /// Attempts to hold an atomic bundle under a predetermined promise ID.
    Hold {
        /// Identity generated by the control API.
        promise_id: PromiseId,
        /// Claims to reserve atomically.
        bundle: Bundle,
        /// First timestamp at which the hold is expired.
        expires_at: Timestamp,
    },
    /// Attempts each alternative bundle in order under one predetermined promise ID.
    HoldOneOf {
        /// Identity generated by the control API.
        promise_id: PromiseId,
        /// Ordered alternatives from which the first feasible bundle is held.
        choice: Choice,
        /// First timestamp at which the hold is expired.
        expires_at: Timestamp,
    },
    /// Commits a live hold.
    Commit {
        /// Promise to commit.
        promise_id: PromiseId,
        /// Required current promise version.
        expected_version: Version,
    },
    /// Releases a live promise.
    Release {
        /// Promise to release.
        promise_id: PromiseId,
        /// Required current promise version.
        expected_version: Version,
    },
    /// Atomically replaces a live promise.
    Replace {
        /// Promise whose identity is preserved.
        promise_id: PromiseId,
        /// Required current promise version.
        expected_version: Version,
        /// Complete replacement bundle.
        new_bundle: Bundle,
        /// Requested live state after replacement.
        new_state: ReplacementState,
    },
    /// Processes every hold whose deadline has been reached.
    ProcessExpirations,
}

/// The operation-specific response produced by applying a [`Command`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CommandResult {
    /// A resource pool was created.
    ResourcePoolCreated {
        /// Identity supplied by the command.
        resource_pool_id: ResourcePoolId,
    },
    /// A capacity revision was applied.
    CapacityRevised(CapacityRevisionOutcome),
    /// A hold was accepted or found unavailable.
    HoldCompleted(HoldOutcome),
    /// An ordered choice was held or every alternative was unavailable.
    ChoiceCompleted(ChoiceOutcome),
    /// A promise was committed.
    PromiseCommitted {
        /// Committed promise.
        promise_id: PromiseId,
        /// New local version.
        version: Version,
    },
    /// A promise was released.
    PromiseReleased {
        /// Released promise.
        promise_id: PromiseId,
        /// New local version.
        version: Version,
    },
    /// A replacement was accepted or found unavailable.
    PromiseReplaced(ReplaceOutcome),
    /// Due expirations were processed.
    ExpirationsProcessed {
        /// Number of holds expired by this command.
        expired_count: usize,
    },
}
